name: Deploy Documentation and Livrable to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Documentation and Livrable to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for deploying to GitHub Pages

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment for Sphinx
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies for Sphinx
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme

      # Build the Sphinx documentation
      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html source source/_build/html

      # Prepare Livrable files
      - name: Prepare Livrable files
        run: |
          mkdir -p livrable
          cp "Livrables/Livrable_1/Livrable1.html" livrable/index.html
          cp "Livrables/Livrable_1/Livrable1.md" livrable/
          cp "Livrables/Livrable_1/complexite_spaciale.png" livrable/

      # Prepare Documentation files
      - name: Prepare Documentation files
        run: |
          mkdir -p documentation
          cp -r source/_build/html/* documentation/

      # Add intermediate page
      - name: Add intermediate page
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Groupe01-RO</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      margin-top: 50px;
                  }
                  a {
                      display: inline-block;
                      margin: 20px;
                      padding: 15px 30px;
                      font-size: 18px;
                      text-decoration: none;
                      color: white;
                      background-color: #007BFF;
                      border-radius: 5px;
                  }
                  a:hover {
                      background-color: #0056b3;
                  }
              </style>
          </head>
          <body>
              <h1>Bienvenue sur le projet Groupe01-RO</h1>
              <p>Choisissez où vous voulez aller :</p>
              <a href="./documentation/index.html">Documentation</a>
              <a href="./livrable/index.html">Livrable</a>
          </body>
          </html>' > index.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .